### ISSUE TITLE
Android CCLabelTTF become black rect when updating it from background.

### ISSUE THREAD

**Issue by daniaDlbani** [c0i/cocos2d-x-v2#1]
My game is built with cocos2dx 2.2.6 and I have a download process running even if the app is in background so I'm updating progress label and other button depending on the download state. However doing so then back to foreground make the label a black box. I saw a similar issue reported to cocos2dx v3. however the structure is too different and I'm not able to make a similar changes to the cclabel file. Do you have any suggestion?

bug fixing for v3:
https://github.com/cocos2d/cocos2d-x/pull/10162/commits

**Comment by yinjimmy** [comment]
I think you can try

```
void CCScheduler::performFunctionInCocosThread(const std::function<void ()> &function)
```

https://github.com/c0i/cocos2d-x-v2/commit/bb18e49a443570a81785c0515abb9ca37bf84e02#diff-600d51a010d257101a68a654052a4c6c

**Comment by daniaDlbani** [comment]
Thank you so much @yinjimmy this solve the problem.
