### ISSUE TITLE
How to integrate it with existing cocos2dx 2.2.6

### ISSUE THREAD

**Issue by mobileonekh** [c0i/cocos2d-x-v2#3]
HI,
How to replace this to my existing 2.2.6?
Please give some clue.

Thanks;

**Comment by yinjimmy** [comment]
plz try replace with `cocos2dx` and `external` folders and add https://github.com/c0i/cocos2d-x-v2/tree/master/projects/hello/proj.android-studio folder.

**Comment by mobileonekh** [comment]
Hi, Are you available for freelance work? 
Can you help me migrate my code to 64 bit?

**Comment by yinjimmy** [comment]
Hi, plz contact me via Skype :  `live:jimmy.yin5` .
